### PR TITLE
[VAN-719] use LLVM pass to remove unused functions

### PR DESCRIPTION
**Pull request by tim-hoffman**

### CODE REVIEW

**Comment by tim-hoffman** [comment]
Test `subcmps3` also depends on https://github.com/Veridise/circom/pull/56 for correctness so wait until that one is merged in to update this.

**Comment by tim-hoffman** [comment]
Build currently failing due to `error: unable to download https://veridise-public.cachix.org/nar/...`

**Review by 0xddom — COMMENTED** [review]
The fact that we don't use the main template's run function anywhere does not cause trouble with the DCE pass?

**Comment by tim-hoffman** [comment]
> The fact that we don't use the main template's run function anywhere does not cause trouble with the DCE pass?

I set the main template's "build" and "run" function with `External` linkage so they will not be removed. Everything else has `Internal` so it can be removed.

**Review by 0xddom — APPROVED** [review]

**Review by iangneal — APPROVED** [review]
LGTM too

**Pull request merged**
