### PR TITLE
[VAN-252] Generate source location debug info

### PR DESCRIPTION
**Pull request by tim-hoffman**

### CODE REVIEW

**Review by 0xddom — COMMENTED** [review]
Looking good! Just one question. Is it possible to obtain the column too?

Also, can I see an excerpt of the output?

**Comment by tim-hoffman** [comment]
> Looking good! Just one question. Is it possible to obtain the column too?

It should be possible but the `FileLibrary` class only had an implementation for `get_line` so I started with that. It looks like the `codespan-reporting` library that it uses to get the line number does have a `column_index` function as well that would probably compute it.

> Also, can I see an excerpt of the output?

Yes, I should go ahead and add a test case as well I guess.

**Comment by tim-hoffman** [comment]
Output from https://github.com/Veridise/circom/blob/llvm/compiler-tests/arrays/array3.circom

[array3.ll](https://github.com/Veridise/circom/files/11971629/array3.ll.txt)

**Comment by 0xddom** [comment]
> !19 = !DILocation(line: 235, scope: !16)
That one is a little bit weird but looks like its used in a CreateCmpBucket so its not really important

**Comment by 0xddom** [comment]
@tim-hoffman if adding column info would take you more than a couple hours lets merge this PR and we add it later in another PR

**Comment by tim-hoffman** [comment]
I fixed the weird line number. Forgot to convert byte offset to line number for that bucket.
I also added the `FileLibrary::get_column` function so the rest should be straightforward but will take a good chunk of time since it will require a lot of small additions throughout.

**Pull request merged**
